#!/usr/bin/env python3
"""Add the cross-family cards and apply normalized crosswalks to all cards."""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
from generate_cards import CARDS, COMMON_SAFE, DIRECTORY_MAP, card, render  # noqa: E402


def extra(id, title, family, cwe, capec, aliases, surfaces, platforms, summary, source, sink, signals, refs, provenance, body):
    config_signals = [f"Configuration flags, defaults or error paths can bypass {title.lower()}.", "Inspect deployment, proxy, identity and resource-limit settings that affect the control."]
    architecture_signals = [f"Trace {source} to {sink} across synchronous, asynchronous, alternate-protocol and provider boundaries."]
    record = card(
        id, title, family, cwe, capec, aliases, surfaces, ["any"], ["framework-agnostic"], platforms,
        ["An untrusted or lower-trust input reaches the described boundary.", "A security control is expected at or before the sink but is absent, incomplete or applied on only one path."],
        ["untrusted input to application", "application to privileged/resource sink"],
        {"sources": [source], "transformations": ["decode, normalize or parse input", "application-specific routing"], "controls": ["validation or policy control if present"], "sinks": [sink], "authorization_points": ["the decision point immediately before the sink"]},
        signals, config_signals, architecture_signals,
        ["What exact source and sink are reachable?", "Which control should run before the sink?", "Do alternate protocols, retries or error paths differ?"], COMMON_SAFE, ["The named library or endpoint is only a signal; confirm reachability and the exact sink."],
        ["security boundary bypass", "confidentiality/integrity/availability impact"], ["Severity depends on the asset, privilege and blast radius."], ["Reachability and a controllable input are required; use test fixtures only."],
        ["Enforce the control at the sink-facing service boundary.", "Make policy explicit, deny by default and cover alternate/async paths.", "Add telemetry and bounded failure behaviour."], ["Typed inputs and explicit policy checks.", "Least privilege, isolation and bounded resource use."],
        ["Add a local or staging negative test using a canary and assert the control blocks the unsafe sink."], refs, provenance, body
    )
    record["summary"] = summary
    return record


EXTRA = [
    extra("vuln.http.request-smuggling", "HTTP request smuggling and connection desynchronization", "http-proxy-cache", "CWE-444", ["CAPEC-33"], ["HTTP desync", "client desync"], ["HTTP/1.1", "HTTP/2", "reverse proxy", "API gateway"], ["web", "api", "proxy"], "Different HTTP components parse the same request boundary differently, allowing one connection's bytes to be interpreted as another request.", "request framing headers and connection reuse", "proxy/backend request queue", ["Front proxy and backend use different framing rules", "Connection reuse is enabled without normalization", "HTTP/2 downgrade or alternate parser path is unreviewed"], ["https://cwe.mitre.org/data/definitions/444.html", "https://portswigger.net/web-security/request-smuggling"], ["sources/manifest.yaml:portswigger-academy", "sources/manifest.yaml:mitre-cwe"], "Request smuggling is a parser differential. Review the entire proxy chain, normalize framing, and use bounded connection handling. Safe validation is a local proxy/backend harness that compares parsed request counts; do not send ambiguous framing to systems outside the lab."),
    extra("vuln.http.cache-poisoning", "Unsafe cache keying and cache poisoning", "http-proxy-cache", "CWE-444", [], ["web cache poisoning", "cache confusion"], ["HTTP", "CDN", "reverse proxy", "browser"], ["web", "api", "cdn"], "A shared cache stores or serves a response under a key that omits security-relevant request state or accepts attacker-influenced metadata.", "request headers, query or host metadata", "shared cache response", ["Cache key excludes host/query/auth-relevant state", "Unkeyed header changes response", "Private response is stored as public"], ["https://portswigger.net/web-security/web-cache-poisoning"], ["sources/manifest.yaml:portswigger-academy"], "Cache integrity fails when the cache's identity model is weaker than the origin's response variability. Define cacheability, key all response-affecting state, and never share personalized or security-sensitive responses by default."),
    extra("vuln.network.ssrf", "Server-side request forgery and unsafe URL fetching", "ssrf-network", "CWE-918", ["CAPEC-664"], ["SSRF", "cloud metadata access", "unsafe webhook fetch"], ["webhook", "URL preview", "import", "proxy", "API"], ["server", "cloud", "network"], "A user-controlled or third-party-controlled URL reaches a server-side network client without a robust destination policy and redirect/rebinding defense.", "request URL, webhook target or third-party redirect", "server-side HTTP client and reachable network", ["URL parsed more than once", "Redirects followed without revalidation", "DNS resolution and connection destination are not bound", "Internal/cloud ranges reachable from service identity"], ["https://cwe.mitre.org/data/definitions/918.html", "https://owasp.org/API-Security/editions/2023/en/0xa6-server-side-request-forgery/"], ["sources/manifest.yaml:owasp-api", "sources/manifest.yaml:mitre-cwe"], "SSRF is a network-boundary failure, not merely a string validation issue. Resolve and authorize destinations in a controlled client, re-check redirects and connection results, isolate the worker, and remove ambient cloud credentials."),
    extra("vuln.files.path-traversal", "Path traversal and unsafe file resolution", "files-paths-storage", "CWE-22", ["CAPEC-126", "CAPEC-139"], ["directory traversal", "Zip Slip", "path traversal"], ["file download", "archive extraction", "template/file import"], ["server", "container", "worker"], "Untrusted path-like data changes the file selected or written outside the intended root after incomplete normalization or archive extraction.", "path parameter, archive member name or filename", "filesystem read/write", ["Check-before-canonicalize order", "String prefix check instead of resolved-path containment", "Archive extraction trusts member names", "Symlink or mount changes the effective root"], ["https://cwe.mitre.org/data/definitions/22.html", "https://portswigger.net/web-security/file-path-traversal"], ["sources/manifest.yaml:patt", "sources/manifest.yaml:portswigger-academy", "sources/manifest.yaml:mitre-cwe"], "Path safety is a canonicalization and containment property. Resolve against a fixed directory, enforce containment after resolution, reject links where appropriate, and use a dedicated low-privilege storage worker."),
    extra("vuln.files.upload", "Unrestricted file upload and unsafe media processing", "files-paths-storage", "CWE-434", ["CAPEC-43"], ["unrestricted upload", "polyglot upload"], ["file upload", "image/PDF import", "object storage"], ["web", "api", "worker"], "An untrusted actor can store or process a file whose type, name, size or parser behaviour exceeds the intended upload contract.", "multipart body, object key or remote import", "filesystem/object storage/media parser/browser delivery", ["Trust MIME type or filename alone", "Upload directory executable or same-origin", "Parser runs with service privileges", "No size/complexity/quota limit"], ["https://cwe.mitre.org/data/definitions/434.html", "https://owasp.org/www-community/vulnerabilities/Unrestricted_File_Upload"], ["sources/manifest.yaml:patt", "sources/manifest.yaml:mitre-cwe"], "Uploads need independent validation, storage isolation and safe processing. Treat filename, MIME and content as untrusted; re-encode where appropriate, serve from a separate origin, and scan/parse in a least-privilege bounded worker."),
    extra("vuln.serialization.unsafe-deserialization", "Unsafe deserialization and object graph execution", "serialization-parsers", "CWE-502", ["CAPEC-586"], ["insecure deserialization", "unsafe object deserialization"], ["API", "queue", "cache", "session", "file import"], ["server", "worker", "runtime"], "Untrusted serialized data is turned into objects or behaviour without a safe type allowlist, integrity check or isolated parser boundary.", "request, queue, cache or uploaded serialized value", "deserializer, gadget-capable runtime or object rehydration", ["Polymorphic type metadata enabled", "Deserializer accepts arbitrary classes", "Integrity/authenticity checked after deserialization", "Object hooks execute during rehydration"], ["https://cwe.mitre.org/data/definitions/502.html", "https://portswigger.net/web-security/deserialization"], ["sources/manifest.yaml:portswigger-academy", "sources/manifest.yaml:mitre-cwe"], "Prefer data-only formats and explicit schemas. If object rehydration is required, use an allowlist, authenticated envelope, bounded depth/size and an isolated low-privilege process with no ambient secrets."),
    extra("vuln.serialization.prototype-pollution", "Prototype or class pollution across object merges", "serialization-parsers", "CWE-1321", [], ["prototype pollution", "class pollution"], ["JSON API", "configuration", "templating", "request merge"], ["server", "browser", "runtime"], "Untrusted keys or object graphs alter shared prototypes, classes or inherited configuration that later code treats as trusted.", "JSON/body/query keys or configuration fragments", "deep merge, object assignment or class metadata", ["Recursive merge accepts inherited/special keys", "Default object prototypes are shared across requests", "Polluted configuration reaches a sensitive sink"], ["https://cwe.mitre.org/data/definitions/1321.html"], ["sources/manifest.yaml:mitre-cwe", "sources/manifest.yaml:patt"], "Use schema-driven parsing and own-property checks, reject special keys where applicable, avoid shared mutable prototypes, and keep configuration values typed before they reach security decisions."),
    extra("vuln.business.race-condition", "Race condition and TOCTOU in stateful workflows", "business-logic-state", "CWE-362", ["CAPEC-26", "CAPEC-29"], ["race condition", "TOCTOU", "double spend"], ["payment", "quota", "invite", "job", "file", "API"], ["server", "database", "distributed"], "A security or business invariant is checked separately from the state change, allowing concurrent requests or workers to observe and commit an invalid interleaving.", "concurrent request, queue delivery or filesystem state", "check-then-use, transaction or distributed lock", ["Read and write are separate transactions", "Idempotency key is accepted but not atomically claimed", "Lock scope/expiry does not cover the invariant", "Retry duplicates side effect"], ["https://cwe.mitre.org/data/definitions/362.html"], ["sources/manifest.yaml:mitre-cwe", "sources/manifest.yaml:patt"], "Make the invariant atomic: database constraint/transaction, compare-and-set, idempotency record, or a correctly scoped lock. Test with deterministic concurrency in a local harness and assert one committed outcome."),
    extra("vuln.business.workflow", "Improper enforcement of business workflow", "business-logic-state", "CWE-841", [], ["business logic flaw", "workflow bypass"], ["checkout", "approval", "registration", "refund", "API"], ["web", "api", "mobile"], "A user can reach a valid-looking state transition without satisfying the business prerequisites, ordering, actor separation or value constraints.", "request fields, workflow state or client-supplied status", "state transition and business side effect", ["Server trusts client state or price", "Transition endpoint lacks predecessor-state check", "Approval and execution share one principal", "Negative/duplicate values not rejected"], ["https://cwe.mitre.org/data/definitions/841.html"], ["sources/manifest.yaml:patt", "sources/manifest.yaml:mitre-cwe"], "Encode the workflow as a server-side state machine. Derive sensitive values from trusted records, require actor separation where needed, enforce idempotence and log every transition."),
    extra("vuln.availability.resource-exhaustion", "Unbounded resource consumption and algorithmic DoS", "availability-resources", "CWE-400", ["CAPEC-125"], ["resource exhaustion", "ReDoS", "unrestricted resource consumption"], ["API", "parser", "search", "regex", "batch"], ["server", "worker", "cloud"], "Untrusted input or a tenant-controlled workload can consume disproportionate CPU, memory, connections, storage or downstream quota.", "request size, regex/query, batch, file or model context", "parser, algorithm, queue, downstream call or model inference", ["Missing body/depth/time limits", "Catastrophic backtracking or expensive query plan", "Retries amplify work", "Per-tenant quota absent"], ["https://cwe.mitre.org/data/definitions/400.html", "https://owasp.org/API-Security/editions/2023/en/0xa4-unrestricted-resource-consumption/"], ["sources/manifest.yaml:owasp-api", "sources/manifest.yaml:mitre-cwe"], "Budget each resource at each boundary: input size, parse depth, CPU/time, concurrency, fan-out, retries, tokens and storage. Fail closed and measure per principal/tenant."),
    extra("vuln.secrets.hardcoded", "Hardcoded secrets and secret residue", "information-secrets-privacy", "CWE-798", [], ["hardcoded secret", "credential in source", "secret leak"], ["source", "config", "CI", "logs", "artifact"], ["repository", "build", "runtime"], "A credential, private key, token or sensitive connection value is embedded in source, configuration, logs, test fixtures or build artifacts beyond its intended exposure.", "source/config/log/artifact content", "authentication, cloud API or downstream connection", ["Literal token/secret-like value", "Secret copied into image, bundle or log", "Test fixture uses a real-looking credential", "Rotation cannot identify all copies"], ["https://cwe.mitre.org/data/definitions/798.html", "https://github.com/gitleaks/gitleaks"], ["sources/manifest.yaml:gitleaks", "sources/manifest.yaml:mitre-cwe", "sources/manifest.yaml:seclists"], "Remove and rotate exposed credentials, use a managed secret store or short-lived identity, prevent secret logging and scan history/artifacts. A scanner match must be triaged for reachability and validity."),
    extra("vuln.crypto.randomness", "Predictable randomness or weak cryptographic usage", "crypto-transport", "CWE-338", [], ["predictable token", "weak PRNG", "nonce reuse"], ["session", "reset", "CSRF", "signature", "key generation"], ["server", "mobile", "firmware"], "Security-sensitive tokens, keys, nonces or identifiers are generated or used with insufficient entropy, unsafe reuse or an inappropriate primitive.", "time/user/process state or generated token", "authentication, authorization or cryptographic verification", ["Non-cryptographic RNG for security token", "Nonce/IV reuse", "Custom crypto or unchecked verification result", "Key material derived from predictable state"], ["https://cwe.mitre.org/data/definitions/338.html", "https://cwe.mitre.org/data/definitions/330.html"], ["sources/manifest.yaml:mitre-cwe"], "Use platform CSPRNGs and reviewed primitives, define nonce/key lifecycle, verify signatures before claims are trusted, and document entropy/rotation requirements."),
    extra("vuln.supply.dependency-risk", "Vulnerable, confused or unpinned dependency supply chain", "supply-chain-cicd", "CWE-1104", [], ["vulnerable component", "dependency confusion", "typosquatting"], ["package manager", "build", "runtime", "plugin"], ["repository", "CI", "artifact", "runtime"], "The build or runtime resolves an untrusted, vulnerable, ambiguous or mutable dependency without provenance, pinning, review or compensating controls.", "manifest, lockfile, registry metadata or transitive dependency", "package resolution/build/plugin execution", ["Missing lockfile or integrity metadata", "Private/public registry ambiguity", "Install scripts execute with build secrets", "Advisory not connected to deployed version"], ["https://cwe.mitre.org/data/definitions/1104.html", "https://osv.dev/docs/", "https://github.com/ossf/scorecard"], ["sources/manifest.yaml:osv", "sources/manifest.yaml:openssf-scorecard", "sources/manifest.yaml:mitre-cwe"], "Pin and verify dependencies, use trusted registries and provenance, review install/build scripts, maintain SBOM and query OSV/GHSA data at audit time. Do not report an advisory without reachability and version evidence."),
    extra("vuln.supply.ci-cd", "CI/CD workflow trust and artifact integrity failure", "supply-chain-cicd", "CWE-829", [], ["CI injection", "untrusted workflow", "artifact substitution"], ["CI", "SCM", "release", "artifact"], ["repository", "CI runner", "registry", "production"], "Untrusted repository content, event metadata, action/plugin, runner or artifact can influence a privileged build or deployment without isolation and integrity controls.", "pull request metadata, branch/tag, build script or artifact", "CI runner, signing, registry or deployment action", ["Untrusted event runs with write/cloud secrets", "Mutable action/container reference", "Artifact not signed or bound to commit", "Runner/workspace reused across trust levels"], ["https://cwe.mitre.org/data/definitions/829.html", "https://github.com/ossf/scorecard"], ["sources/manifest.yaml:openssf-scorecard", "sources/manifest.yaml:mitre-cwe"], "Separate trust levels, use least-privilege ephemeral runners, pin actions/images, protect release refs, sign and verify artifacts, and keep secrets out of untrusted jobs."),
    extra("vuln.cloud.iam", "Cloud IAM over-privilege and resource-policy drift", "cloud-containers-infra", "CWE-732", ["CAPEC-1"], ["cloud IAM", "public bucket", "overprivileged role"], ["cloud API", "storage", "metadata", "serverless"], ["cloud", "IAM", "storage"], "A workload, user or resource policy grants more identity, network, data or control-plane capability than the intended task requires.", "request identity, workload role or resource policy", "cloud control-plane/API or sensitive data store", ["Wildcard actions/resources", "Public or cross-account resource policy", "Metadata credentials reachable from untrusted path", "Environment role reused across services"], ["https://cwe.mitre.org/data/definitions/732.html", "https://owasp.org/Top10/2025/A01_2025-Broken_Access_Control/"], ["sources/manifest.yaml:mitre-cwe", "sources/manifest.yaml:owasp-asvs"], "Model identity and resource policies together. Apply least privilege, condition keys, private endpoints, workload identity, credential rotation and continuous policy testing; remove ambient credentials from untrusted workers."),
    extra("vuln.container.kubernetes", "Container and Kubernetes isolation/configuration failure", "cloud-containers-infra", "CWE-250", [], ["container breakout", "Kubernetes misconfiguration", "privileged pod"], ["container", "Kubernetes", "Helm", "service mesh"], ["container", "kubernetes", "cloud"], "A container or workload receives host, cluster, network or identity capabilities beyond its intended boundary through configuration or runtime defaults.", "image/deployment manifest, service account or workload input", "host kernel, Kubernetes API, cloud metadata or sibling service", ["Privileged/root pod", "HostPath or host network exposure", "Broad service account token", "Unbounded egress or admission bypass"], ["https://cwe.mitre.org/data/definitions/250.html", "https://kubernetes.io/docs/concepts/security/"], ["sources/manifest.yaml:mitre-cwe"], "Use non-root/read-only workloads, drop capabilities, restrict service accounts, namespaces, network egress and host mounts, enforce admission policy, pin images and patch the host/runtime."),
    extra("vuln.native.memory-safety", "Memory-safety violation at native or FFI boundary", "native-memory", "CWE-119", ["CAPEC-100"], ["buffer overflow", "use-after-free", "unsafe FFI"], ["native service", "FFI", "parser", "embedded"], ["C", "C++", "Rust", "Swift", "Kotlin/NDK"], "Untrusted sizes, lifetimes, formats or pointers reach native code without bounds, ownership, lifetime or integer-safety guarantees.", "network/file/input buffer or FFI value", "native memory access, parser or unsafe callback", ["Unchecked length arithmetic", "Raw pointer crossing FFI without ownership contract", "Use-after-free or double release path", "Unsafe parser runs with process privileges"], ["https://cwe.mitre.org/data/definitions/119.html", "https://cwe.mitre.org/data/definitions/787.html"], ["sources/manifest.yaml:mitre-cwe"], "Prefer memory-safe APIs, explicit ownership and checked arithmetic. Isolate parsers, fuzz only bounded local fixtures, use sanitizers/ASan-like tooling in CI and keep native workers least privileged."),
    extra("vuln.mobile.secure-storage-ipc", "Mobile insecure storage, IPC and exported component", "mobile", "CWE-922", [], ["mobile data storage", "exported component", "insecure IPC"], ["Android", "iOS", "deep link", "WebView", "IPC"], ["android", "ios", "mobile"], "Sensitive mobile data or privileged component is exposed through storage, logs, backup, IPC, deep links or exported app surfaces without caller and data-boundary controls.", "intent/deep link/IPC input or local storage", "exported component, WebView bridge, key-value store or log", ["Exported activity/service/provider without permission", "Sensitive value in preferences/log/backup", "WebView bridge trusts origin", "Deep link performs action without user/context binding"], ["https://mas.owasp.org/", "https://cwe.mitre.org/data/definitions/922.html"], ["sources/manifest.yaml:owasp-mobile", "sources/manifest.yaml:mitre-cwe"], "Use platform keystore/keychain, minimize exported components, validate caller and origin, bind high-impact actions to explicit user intent and exclude secrets from logs/backups/screenshots."),
    extra("vuln.ai.prompt-injection", "Direct and indirect prompt injection / goal hijack", "ai-llm-rag-agents", "CWE-1427", ["CAPEC-1548"], ["LLM01", "indirect prompt injection", "agent goal hijack"], ["LLM", "RAG", "agent", "email/document", "MCP"], ["ai", "agent", "rag", "mcp"], "Untrusted text, retrieved content, tool output or multimodal data is interpreted as an instruction that can override the intended task, policy or authority hierarchy.", "user/document/email/web/API/tool content", "prompt/context assembly, planner or tool selector", ["Instruction and data share one channel", "Retrieved text is trusted by role or formatting", "Model output directly changes plan/tool arguments", "No provenance, delimiters or policy enforcement outside the model"], ["https://genai.owasp.org/llmrisk/llm01-prompt-injection/", "https://atlas.mitre.org/"], ["sources/manifest.yaml:owasp-genai", "sources/manifest.yaml:hacktricks"], "Prompt injection is a data/authority confusion. Treat all external content as untrusted data, preserve provenance, enforce typed tool policies in ordinary code, and require explicit confirmation for high-impact actions. A refusal is not a security boundary."),
    extra("vuln.ai.rag-cross-tenant", "RAG/vector retrieval cross-tenant disclosure", "ai-llm-rag-agents", "CWE-639", [], ["vector store leakage", "embedding access control", "LLM02"], ["RAG", "vector DB", "search", "multi-tenant"], ["ai", "rag", "database", "cloud"], "Retrieval or context assembly returns documents, embeddings or metadata outside the caller's tenant, purpose or data classification boundary.", "query, embedding, document metadata or filter", "retriever/vector store/context window", ["Tenant filter applied after retrieval", "Embedding index lacks tenant partition", "Cache key omits tenant/user", "Model can cite or summarize hidden context"], ["https://genai.owasp.org/llmrisk/llm08-vector-and-embedding-weaknesses/", "https://cwe.mitre.org/data/definitions/639.html"], ["sources/manifest.yaml:owasp-genai", "sources/manifest.yaml:mitre-cwe"], "Authorize retrieval before data enters model context. Partition or filter by tenant and purpose at the datastore boundary, bind cache keys to identity, minimize citations and test with synthetic cross-tenant canaries."),
    extra("vuln.ai.excessive-agency", "Excessive agency and over-privileged tool use", "ai-llm-rag-agents", "CWE-250", ["CAPEC-122"], ["LLM06", "tool misuse", "over-privileged agent"], ["agent", "tool calling", "MCP", "automation"], ["ai", "agent", "mcp", "cloud"], "An agent can select tools, identities, destinations or arguments with more authority or side-effect scope than the user-approved task requires.", "model plan/tool arguments/user goal", "tool/MCP call, cloud API, filesystem or deployment action", ["Tool exposed without capability scope", "Model-generated arguments not schema-validated", "No per-action authorization or confirmation", "Service identity broader than task"], ["https://genai.owasp.org/llmrisk/llm06-excessive-agency/", "https://genai.owasp.org/resource/securing-agentic-applications-guide-1-0/"], ["sources/manifest.yaml:owasp-genai", "sources/manifest.yaml:hacktricks"], "Keep agent capabilities narrow and explicit. Validate arguments as data, authorize destination/object/action outside the model, use separate identities, dry-run/preview and confirmation for consequential changes, and log provenance."),
    extra("vuln.ai.output-handling", "Unsafe handling of model output at downstream sinks", "ai-llm-rag-agents", "CWE-116", ["CAPEC-63"], ["LLM05", "improper output handling"], ["LLM", "API", "HTML", "SQL", "shell", "workflow"], ["ai", "web", "api", "worker"], "Model output is treated as trusted markup, query text, code, routing metadata or tool arguments without schema validation and contextual encoding.", "model output or tool result", "HTML/DOM, SQL, shell, URL, parser, workflow or user notification", ["Free-form output fed to a privileged parser", "Structured output schema not enforced", "Output displayed without context encoding", "Model-generated URL/command accepted as authority"], ["https://genai.owasp.org/llmrisk/llm05-improper-output-handling/", "https://cwe.mitre.org/data/definitions/116.html"], ["sources/manifest.yaml:owasp-genai", "sources/manifest.yaml:mitre-cwe"], "Treat model output as untrusted input. Use typed schemas, allowlisted enums, contextual encoding, dry-run and human approval for side effects; separate generation from execution."),
    extra("vuln.ai.unsafe-model-loading", "Unsafe model, plugin or artifact loading", "ai-llm-rag-agents", "CWE-502", [], ["model supply chain", "unsafe pickle", "LLM03", "LLM04"], ["MLOps", "model registry", "plugin", "CI"], ["ai", "mlops", "supply-chain", "cloud"], "A model, tokenizer, plugin, adapter or serialized artifact is loaded from an untrusted or mutable source and can execute code, alter behaviour or poison downstream decisions.", "registry URI, model file, plugin metadata or training data", "loader/deserializer, runtime import or inference pipeline", ["Remote artifact loaded without hash/signature/provenance", "Unsafe serialization format", "Plugin executes in training/inference identity", "Data lineage and evaluation absent"], ["https://cwe.mitre.org/data/definitions/502.html", "https://genai.owasp.org/llmrisk/llm03-supply-chain/"], ["sources/manifest.yaml:owasp-genai", "sources/manifest.yaml:mitre-cwe"], "Pin and verify artifacts, prefer data-only formats, isolate loaders, restrict network/secrets, maintain provenance/SBOM and evaluate behaviour before promotion. Do not load unknown models in a production identity."),
    extra("vuln.information.logging", "Sensitive information disclosure through logs and errors", "information-secrets-privacy", "CWE-532", [], ["log leak", "error disclosure", "debug exposure"], ["API", "logs", "tracing", "errors", "AI telemetry"], ["server", "cloud", "CI"], "Sensitive values, credentials, personal data, prompts, retrieved documents or internal details cross into logs, traces, error responses or monitoring systems without minimization and access control.", "request, exception, prompt/context or secret", "logger, trace exporter, error response or dashboard", ["Full request/response logging", "Stack traces returned to client", "Prompt/RAG/tool content stored without classification", "Redaction is regex-only and applied after serialization"], ["https://cwe.mitre.org/data/definitions/532.html", "https://owasp.org/Top10/2025/A09_2025-Logging_Alerting_Failures/"], ["sources/manifest.yaml:mitre-cwe", "sources/manifest.yaml:owasp-asvs"], "Classify and minimize telemetry, redact at source, separate security audit events from content logs, protect access/retention and test error paths with synthetic secrets and PII markers."),
    extra("vuln.configuration.fail-open", "Fail-open exceptional conditions and unsafe defaults", "configuration-deployment", "CWE-636", [], ["fail open", "unsafe default", "exception bypass"], ["auth", "network", "parser", "feature flag", "deployment"], ["server", "cloud", "container", "mobile"], "A timeout, parse error, missing configuration, dependency failure or unexpected state grants access or continues a sensitive operation instead of failing safely.", "exception, timeout, absent config or dependency response", "fallback branch, feature flag or authorization decision", ["Catch-all exception returns success", "Missing policy treated as allow", "Default credentials/debug mode", "Circuit breaker bypasses authorization or audit"], ["https://cwe.mitre.org/data/definitions/636.html", "https://owasp.org/Top10/2025/A10_2025-Mishandling_of_Exceptional_Conditions/"], ["sources/manifest.yaml:mitre-cwe", "sources/manifest.yaml:owasp-asvs"], "Define fail-closed behaviour per operation, distinguish availability fallback from security decision, make defaults explicit, alert on policy/config errors and add tests for timeouts, malformed inputs and missing dependencies."),
]

EXTRA += [
    extra("vuln.injection.command", "OS command injection", "injection", "CWE-78", ["CAPEC-77"], ["shell injection", "process argument injection"], ["web", "job", "automation", "agent tool"], ["server", "worker", "container"], "Untrusted data changes a process command or argument at a shell/process execution sink.", "request, file, environment or model/tool argument", "OS process execution", ["Shell command built by concatenation", "Argument boundary lost through a shell", "Process inherits secrets or broad filesystem/network access"], ["https://cwe.mitre.org/data/definitions/78.html"], ["sources/manifest.yaml:patt", "sources/manifest.yaml:mitre-cwe"], "Pass a fixed executable and typed argument vector to a process API, avoid shell interpretation, validate allowed operations, and isolate the worker with no ambient secrets."),
    extra("vuln.injection.template", "Server-side template injection", "injection", "CWE-1336", ["CAPEC-77"], ["SSTI", "template source injection"], ["web", "email", "reporting", "document"], ["server", "worker"], "Untrusted content is compiled or interpreted as server-side template source instead of remaining a value.", "request, stored field or uploaded template", "template engine compilation/rendering", ["User value passed as template source", "Dynamic template names or extension functions", "Template context exposes filesystem, network or process objects"], ["https://cwe.mitre.org/data/definitions/1336.html", "https://portswigger.net/web-security/server-side-template-injection"], ["sources/manifest.yaml:patt", "sources/manifest.yaml:portswigger-academy", "sources/manifest.yaml:mitre-cwe"], "Keep templates code-owned and pass untrusted values through contextual variables. If user-authored templates are required, use a restricted language and isolated renderer with explicit capabilities."),
    extra("vuln.injection.expression", "Expression-language injection", "injection", "CWE-917", ["CAPEC-77"], ["EL injection", "SpEL", "OGNL"], ["web", "configuration", "policy", "workflow"], ["server", "worker"], "Untrusted text is evaluated by an expression language with access to objects, methods or properties beyond the intended data model.", "request, configuration or model-generated expression", "expression evaluator or policy engine", ["Dynamic expression evaluation", "Method/property access not allowlisted", "Evaluation context contains services or secrets"], ["https://cwe.mitre.org/data/definitions/917.html"], ["sources/manifest.yaml:mitre-cwe", "sources/manifest.yaml:patt"], "Prefer typed predicates and fixed policy definitions. If expressions are required, use a minimal allowlisted grammar and context with no ambient service, filesystem or network capability."),
    extra("vuln.api.graphql", "GraphQL field authorization and query complexity failure", "api-protocols", "CWE-285", [], ["GraphQL authz", "GraphQL introspection", "query complexity"], ["GraphQL", "API", "federation"], ["api", "web", "mobile"], "A GraphQL operation exposes fields, resolvers or resource cost without enforcing object/property/function policy and bounded query complexity.", "query document, variables and resolver context", "parser, resolver, data loader or federation hop", ["Authz only at route level", "Resolver returns fields beyond caller scope", "Aliases/fragments/depth/batching bypass limits", "Federated service trusts upstream claims"], ["https://owasp.org/API-Security/editions/2023/en/0xa3-broken-object-property-level-authorization/"], ["sources/manifest.yaml:owasp-api", "sources/manifest.yaml:mitre-cwe"], "Authorize each sensitive field/object in the resolver or data layer, apply tenant-aware loaders, validate schema and complexity/depth limits, and make federation trust explicit."),
    extra("vuln.api.websocket", "WebSocket origin, authentication and message authorization failure", "api-protocols", "CWE-346", [], ["WebSocket auth", "CSWSH", "message-level authorization"], ["WebSocket", "realtime API", "browser"], ["api", "browser", "mobile"], "A persistent connection or message handler trusts handshake state, origin or channel membership without rechecking the principal's right to each action/data stream.", "handshake headers, cookies and message payload", "connection upgrade, channel subscription or message handler", ["Origin not validated for cookie-authenticated browser clients", "Connection auth not bound to message/channel", "Subscription names map directly to tenant/object data", "Reconnect/resume bypasses authorization"], ["https://portswigger.net/web-security/websockets"], ["sources/manifest.yaml:portswigger-academy", "sources/manifest.yaml:mitre-cwe"], "Validate origin and authentication at upgrade, authorize channel/object/message actions, expire/revoke connections and treat reconnect tokens as bearer credentials."),
    extra("vuln.internal.credential-relay", "Credential relay and confused-deputy trust across internal services", "internal-enterprise", "CWE-441", ["CAPEC-664"], ["credential relay", "confused deputy", "internal trust"], ["LDAP", "Kerberos", "NTLM", "SMB", "service-to-service"], ["enterprise", "windows", "linux", "network"], "A service accepts a caller-controlled destination or identity-bearing request and forwards credentials or authority across an internal trust boundary.", "name resolution, referral, URL or forwarded identity", "directory/file/message service or internal proxy", ["Unsigned channel or missing binding", "Service forwards ambient credentials", "Internal proxy accepts arbitrary destination", "Trust inferred from network location"], ["https://cwe.mitre.org/data/definitions/441.html"], ["sources/manifest.yaml:internal-all-the-things", "sources/manifest.yaml:mitre-cwe"], "Bind identity to the intended service, require signing/channel protection, restrict referrals/destinations, remove ambient credentials and isolate internal proxy capabilities. Test only in a dedicated lab."),
    extra("vuln.hardware.firmware-update", "Unsigned or rollbackable firmware update", "hardware-firmware-iot", "CWE-494", [], ["firmware update", "secure boot", "rollback attack"], ["firmware", "IoT", "OTA", "bootloader"], ["hardware", "firmware", "embedded"], "A device accepts firmware or configuration without strong authenticity/integrity, version/rollback policy or recovery validation.", "update URL/package, removable media or local debug path", "bootloader, updater or privileged firmware installer", ["Hash without trusted signature", "Mutable update source", "Rollback protection absent", "Debug/update mode exposed in production"], ["https://cwe.mitre.org/data/definitions/494.html"], ["sources/manifest.yaml:hardware-all-the-things", "sources/manifest.yaml:mitre-cwe"], "Verify signed manifests and image chains, enforce anti-rollback, use authenticated transport, protect update keys, restrict debug paths and test recovery on owned hardware."),
    extra("vuln.web3.reentrancy", "Smart-contract reentrancy and unsafe external call ordering", "web3-smart-contracts", "CWE-841", [], ["reentrancy", "checks-effects-interactions"], ["smart contract", "wallet", "token", "bridge"], ["blockchain", "smart-contract", "dapp"], "A contract makes an external call before updating an invariant, allowing control to re-enter or observe an intermediate state.", "transaction calldata or external contract callback", "external call, balance/state update or oracle-dependent branch", ["External call before state update", "Untrusted callback contract", "Invariant not protected by guard/accounting", "Upgrade/admin path changes call target"], ["https://cwe.mitre.org/data/definitions/841.html"], ["sources/manifest.yaml:hacktricks", "sources/manifest.yaml:mitre-cwe"], "Use checks-effects-interactions, reentrancy guards where appropriate, pull payments, explicit invariants and bounded external trust. Test against local mocked contracts, not public networks."),
    extra("vuln.crypto.transport", "Cleartext or unauthenticated transport of sensitive data", "crypto-transport", "CWE-319", [], ["cleartext transmission", "TLS misconfiguration"], ["HTTP", "database", "message", "mobile", "internal service"], ["web", "api", "cloud", "mobile", "iot"], "Sensitive data or credentials cross a network without authenticated confidentiality/integrity or with downgrade/hostname-validation controls disabled.", "request, secret or service message", "socket, proxy, database or provider connection", ["TLS disabled/optional", "Certificate/hostname verification skipped", "Legacy protocol fallback", "Sensitive endpoint accessible over cleartext"], ["https://cwe.mitre.org/data/definitions/319.html"], ["sources/manifest.yaml:mitre-cwe", "sources/manifest.yaml:owasp-asvs"], "Require modern authenticated transport, validate peer identity, disable insecure fallback, document trust stores and test endpoint/proxy/mobile configurations separately."),
    extra("vuln.privacy.data-minimization", "Excessive collection, retention or secondary use of sensitive data", "information-secrets-privacy", "CWE-359", [], ["privacy leakage", "data minimization", "PII overcollection"], ["API", "logs", "analytics", "RAG", "mobile"], ["web", "cloud", "mobile", "ai"], "The system collects, retains, exposes or reuses personal/sensitive data beyond the stated purpose or access boundary.", "user input, telemetry, prompt/context or provider response", "storage, logs, analytics, retrieval or model provider", ["Whole request/context persisted", "Retention not bounded", "Purpose/tenant classification absent", "Deletion/export path omits derived indexes and logs"], ["https://cwe.mitre.org/data/definitions/359.html"], ["sources/manifest.yaml:mitre-cwe", "sources/manifest.yaml:owasp-genai"], "Minimize fields, classify purpose/tenant, bound retention, propagate deletion, isolate derived data and make provider/log access auditable. Use synthetic privacy markers in tests."),
]

MAPS = {
    "vuln.authorization.idor": {"owasp_mappings": ["A01:2025"], "asvs_mappings": ["V8"], "wstg_mappings": ["WSTG-ATHZ-01", "WSTG-ATHZ-02"], "api_security_mappings": ["API1:2023", "API3:2023"]},
    "vuln.authorization.function-level": {"owasp_mappings": ["A01:2025"], "asvs_mappings": ["V8"], "wstg_mappings": ["WSTG-ATHZ-02"], "api_security_mappings": ["API5:2023"]},
    "vuln.authentication.session": {"owasp_mappings": ["A07:2025"], "asvs_mappings": ["V3"], "wstg_mappings": ["WSTG-SESS-01"], "api_security_mappings": ["API2:2023"]},
    "vuln.authentication.oauth-oidc-jwt": {"owasp_mappings": ["A07:2025"], "asvs_mappings": ["V2", "V3"], "wstg_mappings": ["WSTG-AUTHN-05"]},
    "vuln.injection.sql": {"owasp_mappings": ["A05:2025"], "asvs_mappings": ["V1", "V5"], "wstg_mappings": ["WSTG-INPV-05"], "api_security_mappings": ["API10:2023"]},
    "vuln.injection.xxe": {"owasp_mappings": ["A05:2025"], "asvs_mappings": ["V5"], "wstg_mappings": ["WSTG-INPV-07"]},
    "vuln.injection.template-command": {"owasp_mappings": ["A05:2025"], "asvs_mappings": ["V5"]},
    "vuln.browser.xss": {"owasp_mappings": ["A05:2025"], "asvs_mappings": ["V5", "V6"], "wstg_mappings": ["WSTG-INPV-02", "WSTG-CLNT-01"]},
    "vuln.browser.csrf": {"owasp_mappings": ["A01:2025"], "asvs_mappings": ["V4"], "wstg_mappings": ["WSTG-SESS-05"]},
    "vuln.http.request-smuggling": {"owasp_mappings": ["A05:2025"], "asvs_mappings": ["V13"], "wstg_mappings": ["WSTG-INPV-16"]},
    "vuln.network.ssrf": {"owasp_mappings": ["A05:2025"], "asvs_mappings": ["V12"], "wstg_mappings": ["WSTG-SRVS-19"], "api_security_mappings": ["API6:2023"]},
    "vuln.files.path-traversal": {"owasp_mappings": ["A01:2025"], "asvs_mappings": ["V12"], "wstg_mappings": ["WSTG-ATHZ-01"]},
    "vuln.files.upload": {"owasp_mappings": ["A05:2025"], "asvs_mappings": ["V12"], "wstg_mappings": ["WSTG-BUSL-08"]},
    "vuln.serialization.unsafe-deserialization": {"owasp_mappings": ["A08:2025"], "asvs_mappings": ["V5"], "wstg_mappings": ["WSTG-INPV-12"]},
    "vuln.business.race-condition": {"owasp_mappings": ["A06:2025"], "asvs_mappings": ["V11"]},
    "vuln.business.workflow": {"owasp_mappings": ["A06:2025"], "asvs_mappings": ["V11"], "wstg_mappings": ["WSTG-BUSL-01"]},
    "vuln.availability.resource-exhaustion": {"owasp_mappings": ["A10:2025"], "asvs_mappings": ["V12"], "api_security_mappings": ["API4:2023"]},
    "vuln.supply.dependency-risk": {"owasp_mappings": ["A03:2025"], "asvs_mappings": ["V14"], "wstg_mappings": ["WSTG-CONF-09"]},
    "vuln.supply.ci-cd": {"owasp_mappings": ["A03:2025", "A08:2025"], "asvs_mappings": ["V14"]},
    "vuln.ai.prompt-injection": {"genai_mappings": ["LLM01:2025", "ASI01", "ASI02"]},
    "vuln.ai.rag-cross-tenant": {"genai_mappings": ["LLM02:2025", "LLM08:2025"], "api_security_mappings": ["API1:2023", "API3:2023"]},
    "vuln.ai.excessive-agency": {"genai_mappings": ["LLM06:2025", "ASI02", "ASI03"]},
    "vuln.ai.output-handling": {"genai_mappings": ["LLM05:2025", "ASI02", "ASI05"]},
    "vuln.ai.unsafe-model-loading": {"genai_mappings": ["LLM03:2025", "LLM04:2025"]},
    "vuln.mobile.secure-storage-ipc": {"masvs_mappings": ["MASVS-STORAGE", "MASVS-PLATFORM"], "wstg_mappings": ["WSTG-PLAT-01"]},
    "vuln.injection.command": {"owasp_mappings": ["A05:2025"], "asvs_mappings": ["V5"]},
    "vuln.injection.template": {"owasp_mappings": ["A05:2025"], "asvs_mappings": ["V5"]},
    "vuln.injection.expression": {"owasp_mappings": ["A05:2025"], "asvs_mappings": ["V5"]},
    "vuln.api.graphql": {"owasp_mappings": ["A01:2025", "A10:2025"], "api_security_mappings": ["API3:2023", "API4:2023"]},
    "vuln.api.websocket": {"owasp_mappings": ["A01:2025"], "asvs_mappings": ["V4"], "wstg_mappings": ["WSTG-CLNT-03"]},
    "vuln.internal.credential-relay": {"owasp_mappings": ["A01:2025"], "asvs_mappings": ["V4"]},
    "vuln.hardware.firmware-update": {"owasp_mappings": ["A08:2025"], "masvs_mappings": ["MASVS-RESILIENCE"]},
    "vuln.web3.reentrancy": {"owasp_mappings": ["A06:2025"]},
    "vuln.crypto.transport": {"owasp_mappings": ["A04:2025"], "asvs_mappings": ["V9"]},
    "vuln.privacy.data-minimization": {"owasp_mappings": ["A09:2025"], "genai_mappings": ["LLM02:2025"]},
    "vuln.secrets.data-minimization": {"owasp_mappings": ["A09:2025"], "genai_mappings": ["LLM02:2025"]},
}

RELATED_CWE = {
    "vuln.authorization.idor": ["CWE-862", "CWE-863"],
    "vuln.authorization.function-level": ["CWE-863", "CWE-269"],
    "vuln.authentication.session": ["CWE-613", "CWE-614", "CWE-1004"],
    "vuln.authentication.oauth-oidc-jwt": ["CWE-287", "CWE-346"],
    "vuln.injection.sql": ["CWE-20", "CWE-943"],
    "vuln.injection.xxe": ["CWE-827", "CWE-776"],
    "vuln.injection.command": ["CWE-78", "CWE-20"],
    "vuln.injection.template": ["CWE-94", "CWE-917"],
    "vuln.injection.expression": ["CWE-94", "CWE-20"],
    "vuln.browser.xss": ["CWE-116", "CWE-829"],
    "vuln.browser.csrf": ["CWE-1275"],
    "vuln.http.request-smuggling": ["CWE-436", "CWE-345"],
    "vuln.network.ssrf": ["CWE-441", "CWE-610"],
    "vuln.files.path-traversal": ["CWE-23", "CWE-36", "CWE-73"],
    "vuln.files.upload": ["CWE-20", "CWE-22", "CWE-79"],
    "vuln.serialization.unsafe-deserialization": ["CWE-915", "CWE-1321"],
    "vuln.business.race-condition": ["CWE-367"],
    "vuln.secrets.hardcoded": ["CWE-259", "CWE-321", "CWE-522"],
    "vuln.crypto.randomness": ["CWE-330", "CWE-327"],
    "vuln.supply.dependency-risk": ["CWE-1395", "CWE-1104", "CWE-494"],
    "vuln.cloud.iam": ["CWE-284", "CWE-269"],
    "vuln.native.memory-safety": ["CWE-787", "CWE-125", "CWE-416"],
    "vuln.ai.prompt-injection": ["CWE-20", "CWE-693"],
    "vuln.ai.output-handling": ["CWE-79", "CWE-601"],
    "vuln.configuration.fail-open": ["CWE-693"],
}

RELATED_VULNS = {
    "vuln.authorization.idor": ["vuln.authorization.function-level", "vuln.ai.rag-cross-tenant"],
    "vuln.authentication.session": ["vuln.authentication.oauth-oidc-jwt", "vuln.browser.csrf"],
    "vuln.injection.sql": ["vuln.injection.command", "vuln.injection.expression"],
    "vuln.injection.template": ["vuln.browser.xss", "vuln.injection.expression"],
    "vuln.network.ssrf": ["vuln.cloud.iam", "vuln.api.graphql"],
    "vuln.files.upload": ["vuln.files.path-traversal", "vuln.injection.xxe"],
    "vuln.serialization.unsafe-deserialization": ["vuln.ai.unsafe-model-loading", "vuln.serialization.prototype-pollution"],
    "vuln.supply.dependency-risk": ["vuln.supply.ci-cd", "vuln.ai.unsafe-model-loading"],
    "vuln.ai.prompt-injection": ["vuln.ai.excessive-agency", "vuln.ai.output-handling"],
    "vuln.ai.excessive-agency": ["vuln.authorization.function-level", "vuln.ai.output-handling"],
    "vuln.mobile.secure-storage-ipc": ["vuln.privacy.data-minimization", "vuln.authentication.session"],
}


def main() -> int:
    all_cards = CARDS + EXTRA
    for record in all_cards:
        if record["id"] == "vuln.injection.template":
            record["aliases"] = ["server-side template injection", "template source injection"]
        if record["id"] == "vuln.secrets.data-minimization":
            record["id"] = "vuln.privacy.data-minimization"
        record.update(MAPS.get(record["id"], {}))
        record["related_cwe"] = RELATED_CWE.get(record["id"], [])
        record["related_vulnerabilities"] = RELATED_VULNS.get(record["id"], [])
        path = ROOT / "vulnerabilities" / DIRECTORY_MAP.get(record["family"], record["family"]) / (record["id"].split(".", 2)[-1] + ".md")
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(render(record.copy()), encoding="utf-8")
    print(f"generated {len(all_cards)} atomic cards")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
